#!/bin/sh
#
# Detect SSE2 capability in processor and compiler.
#
# $Id$

TMPFILE=`mktemp -t gost3411-autotest.XXX` || exit 1
trap "rm -f ${TMPFILE} 2>/dev/null" EXIT

cat <<EOF > ${TMPFILE}.c
#include <emmintrin.h>

int main()
{
    __m128i xmm0, xmm1;
    long long r0;
    xmm0 = _mm_cvtsi64_si128((long long) 0x12345678LL);
    xmm1 = _mm_cvtsi64_si128((long long) 0x87654321LL);
    xmm0 = _mm_xor_si128(xmm0, xmm1);
    r0   = _mm_cvtsi128_si64(xmm0);
    if (r0 == 0x95511559LL) return 0;
    return 1;
}
EOF

${CC} ${CFLAGS_AUTO} -o ${TMPFILE} ${TMPFILE}.c 2>/dev/null

if [ ! -x ${TMPFILE} ]; then
    exit 0
fi

${TMPFILE}

if [ $? -eq 0 ]
then

    cat << EOF
#ifndef __GOST3411_HAS_SSE2__
#define __GOST3411_HAS_SSE2__
#endif
EOF

fi

exit 0
