#!/bin/sh
#
# Copyright (c) 2013, Alexey Degtyarev <alexey@renatasystems.org>. 
# All rights reserved.
#
# Activate SUPERCOP stuff when SUPERCOP environment variable is set.
#
# $Id$

if [ ! -z "${SUPERCOP}" ]
then

    cat << EOF
#ifndef SUPERCOP
#define SUPERCOP
#endif
EOF

fi

exit 0
